kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-pipelines-operator
      namespace: openshift-operators
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'preview'

