apiVersion: v1
items:
- apiVersion: user.openshift.io/v1
  kind: Group
  metadata:
    name: developers
    namespace: ""
  users:
  - dev1
  - dev2
- apiVersion: user.openshift.io/v1
  kind: Group
  metadata:
    name: testers
    namespace: ""
  users:
  - tester1
  - tester2
- apiVersion: user.openshift.io/v1
  kind: Group
  metadata:
    name: auditor
    namespace: ""
  users:
  - audit1
  - audit2
- apiVersion: user.openshift.io/v1
  kind: Group
  metadata:
    name: devops-admins
    namespace: ""
  users:
  - devops1
  - devops2
  - devops3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
