apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
- ../../projects/cluster-config/base
- ../../applications/openshift-pipelines-operator/base
- ../../applications/openshift-groups/base
- ../../applications/ingress-controller/base


