apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- odf-machineset.yaml

patchesJson6902:
- target:
    group: machine.openshift.io
    version: v1beta1
    kind: MachineSet
    name: cluster-5vrxc-q4nt9-odf-us-east-2c
    namespace: openshift-machine-api
  path: patch.yaml

