apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: "0"
    machine.openshift.io/memoryMb: "65536"
    machine.openshift.io/vCPU: "16"
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-5vrxc-q4nt9
  name: cluster-odf-us-east-2c
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-5vrxc-q4nt9
      machine.openshift.io/cluster-api-machineset: cluster-5vrxc-q4nt9-odf-us-east-2c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-5vrxc-q4nt9
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-5vrxc-q4nt9-odf-us-east-2c
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/storage: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      providerSpec:
        value:
          ami:
            id: ami-03d9208319c96db0c
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 120
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-zgd5c-8smm7-worker-profile
          instanceType: m5a.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: us-east-2c
            region: us-east-2
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - cluster-zgd5c-8smm7-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - cluster-zgd5c-8smm7-private-us-east-2c
          tags:
          - name: kubernetes.io/cluster/cluster-zgd5c-8smm7
            value: owned
          - name: Stack
            value: project ocp4-cluster-zgd5c
          - name: env_type
            value: ocp4-cluster
          - name: guid
            value: zgd5c
          - name: owner
            value: unknown
          - name: platform
            value: RHPDS
          - name: uuid
            value: f1d61ea6-4481-507b-ba90-049bb07ae77a
          userDataSecret:
            name: worker-user-data
