- op: replace
  path: /metadata/annotations/machine.openshift.io~1memoryMb
  value: "65536"

- op: replace
  path: /metadata/annotations/machine.openshift.io~1vCPU
  value: "16"

- op: replace
  path: /metadata/labels/machine.openshift.io~1cluster-api-cluster
  value: "cluster-xttft-tc6jn"

- op: replace
  path: /spec/replicas
  value: 3

- op: replace
  path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-cluster
  value:  "cluster-xttft-tc6jn"

- op: replace
  path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-machineset
  value: "cluster-xttft-tc6jn-odf-us-east-2c"

- op: replace
  path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-cluster
  value: "cluster-xttft-tc6jn"

- op: replace
  path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-machineset
  value: "cluster-xttft-tc6jn-odf-us-east-2c"

- op: replace
  path: /spec/template/spec/providerSpec/value/ami/id
  value: "ami-03d9208319c96db0c"

- op: replace
  path: /spec/template/spec/providerSpec/value/iamInstanceProfile/id
  value: "cluster-xttft-tc6jn-worker-profile"

- op: replace
  path: /spec/template/spec/providerSpec/value/placement/availabilityZone
  value: "us-east-2c"

- op: replace
  path: /spec/template/spec/providerSpec/value/placement/region
  value: "us-east-2"

- op: replace
  path: /spec/template/spec/providerSpec/value/securityGroups/0/filters/0/values/0
  value: "cluster-xttft-tc6jn-worker-sg"

- op: replace
  path: /spec/template/spec/providerSpec/value/subnet/filters/0/values/0
  value: "cluster-xttft-tc6jn-private-us-east-2c"

- op: replace
  path: /spec/template/spec/providerSpec/value/tags/0/name
  value: "kubernetes.io/cluster/cluster-xttft-tc6jn"

# STACK    
- op: replace
  path: /spec/template/spec/providerSpec/value/tags/1/value
  value: "project ocp4-cluster-xttft"

# GUID    
- op: replace
  path: /spec/template/spec/providerSpec/value/tags/3/value
  value: "xttft"

#UUID    
- op: replace
  path: /spec/template/spec/providerSpec/value/tags/6/value
  value: "35178cf2-7fe3-5c84-bee6-bf54abdf902c"
