kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  sync.yaml: |                                 
    kind: LDAPSyncConfig
    apiVersion: v1
    url: ldaps://myldapserver.example.com:636
    insecure: false
    bindDN: Frsysentid=FIXME,ou=Systems,ou=MyCity,o=internal,dc=example,dc=com
    bindPassword:
      file: "/etc/secrets/bindPassword"
    ca: /etc/ldap-ca/ca.crt
    rfc2307:
        groupsQuery:
            baseDN: "o=internal,dc=example,dc=com"
            scope: sub
            derefAliases: never
            pageSize: 0
            filter: "(|(cn=OCP-ENG-CLUSTERADMIN-PROD)(cn=APP-SUPPORT-TEAM-P01))"
        groupUIDAttribute: dn
        groupNameAttributes: [ cn ]
        groupMembershipAttributes: [ uniquemember ]
        usersQuery:
            baseDN: "o=internal,dc=example,dc=com"
            scope: sub
            derefAliases: never
            pageSize: 0
        userUIDAttribute: dn
        userNameAttributes: [ uid ]
        tolerateMemberNotFoundErrors: false
        tolerateMemberOutOfScopeErrors: false

